In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

In [2]:
df = pd.read_excel("Maricopa.xlsx")
df

,sale_price,area,pool_area,central_AC,fixtures,garage_count,patio_count,single_story,year_built,year_sold,month_sold,zipcode,city,garage_type,wall,roof,patio_type
0,345000,2015,0,1,7,2,1,1,2001,2018,6,85374.0,SURPRISE,Garage,Frame Wood,Concrete Tile,Cover
1,377500,2919,475,1,11,3,1,1,1991,2019,1,85048.0,PHOENIX,Garage,Frame Wood,Concrete Tile,Cover
2,423039,2044,0,1,7,3,1,1,2016,2017,9,85383.0,PEORIA,Garage,Other,Concrete Tile,Cover
3,333341,1754,0,1,7,2,2,1,2016,2016,11,85085.0,PHOENIX,Garage,Other,Concrete Tile,Cover
4,207000,1680,420,1,8,2,1,1,2003,2017,3,85379.0,SURPRISE,Garage,Frame Wood,Concrete Tile,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2173,235500,1656,461,1,6,2,1,1,1973,2016,9,85053.0,PHOENIX,Garage,8 Inch Painted Block,Asphalt Shingle,Slab
2174,765000,2571,450,1,11,2,2,0,1984,2017,10,85258.0,SCOTTSDALE,Garage,Frame Wood,Tile,Cover
2175,465000,2763,500,1,12,2,2,0,1997,2017,8,85284.0,TEMPE,Garage,Frame Wood,Concrete Tile,Cover
2176,270000,1614,0,1,7,2,1,1,1996,2016,4,85248.0,SUN LAKES,Garage,8 Inch Stucco,Concrete Tile,Cover
2177,166000,1738,0,1,6,2,1,1,1979,2017,5,85375.0,SUN CITY WEST,Garage,Frame Wood,Asphalt Shingle,Cover

In [3]:
results = smf.ols("sale_price ~ area + single_story", data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             sale_price   R-squared:                       0.546
Model:                            OLS   Adj. R-squared:                  0.545
Method:                 Least Squares   F-statistic:                     1306.
Date:                Thu, 14 Nov 2024   Prob (F-statistic):               0.00
Time:                        13:59:43   Log-Likelihood:                -28235.
No. Observations:                2178   AIC:                         5.648e+04
Df Residuals:                    2175   BIC:                         5.649e+04
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -8.785e+04   9122.686     -9.630      0.000   -1.06e+05      -7e+04
area           154.8458      3.048     50.795      0.000     148.868     160.824
single_story  7.686e+04   5436.712     14.137      0.000    6.62e+04    8.75e+04
==============================================================================
Omnibus:                      357.956   Durbin-Watson:                   1.951
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1555.333
Skew:                           0.730   Prob(JB):                         0.00
Kurtosis:                       6.874   Cond. No.                     1.03e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [4]:
random = np.random.uniform(0, 1, size=len(df['sale_price']))
df['random'] = random

In [5]:
df

,sale_price,area,pool_area,central_AC,fixtures,garage_count,patio_count,single_story,year_built,year_sold,month_sold,zipcode,city,garage_type,wall,roof,patio_type,random
0,345000,2015,0,1,7,2,1,1,2001,2018,6,85374.0,SURPRISE,Garage,Frame Wood,Concrete Tile,Cover,0.207710
1,377500,2919,475,1,11,3,1,1,1991,2019,1,85048.0,PHOENIX,Garage,Frame Wood,Concrete Tile,Cover,0.433703
2,423039,2044,0,1,7,3,1,1,2016,2017,9,85383.0,PEORIA,Garage,Other,Concrete Tile,Cover,0.990098
3,333341,1754,0,1,7,2,2,1,2016,2016,11,85085.0,PHOENIX,Garage,Other,Concrete Tile,Cover,0.819898
4,207000,1680,420,1,8,2,1,1,2003,2017,3,85379.0,SURPRISE,Garage,Frame Wood,Concrete Tile,Cover,0.886566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2173,235500,1656,461,1,6,2,1,1,1973,2016,9,85053.0,PHOENIX,Garage,8 Inch Painted Block,Asphalt Shingle,Slab,0.216201
2174,765000,2571,450,1,11,2,2,0,1984,2017,10,85258.0,SCOTTSDALE,Garage,Frame Wood,Tile,Cover,0.880557
2175,465000,2763,500,1,12,2,2,0,1997,2017,8,85284.0,TEMPE,Garage,Frame Wood,Concrete Tile,Cover,0.223575
2176,270000,1614,0,1,7,2,1,1,1996,2016,4,85248.0,SUN LAKES,Garage,8 Inch Stucco,Concrete Tile,Cover,0.143281
2177,166000,1738,0,1,6,2,1,1,1979,2017,5,85375.0,SUN CITY WEST,Garage,Frame Wood,Asphalt Shingle,Cover,0.160207

In [6]:
df = df.drop(df[(df.random < 0.5) & (df.single_story == 1)].index)
df

,sale_price,area,pool_area,central_AC,fixtures,garage_count,patio_count,single_story,year_built,year_sold,month_sold,zipcode,city,garage_type,wall,roof,patio_type,random
2,423039,2044,0,1,7,3,1,1,2016,2017,9,85383.0,PEORIA,Garage,Other,Concrete Tile,Cover,0.990098
3,333341,1754,0,1,7,2,2,1,2016,2016,11,85085.0,PHOENIX,Garage,Other,Concrete Tile,Cover,0.819898
4,207000,1680,420,1,8,2,1,1,2003,2017,3,85379.0,SURPRISE,Garage,Frame Wood,Concrete Tile,Cover,0.886566
5,305898,2909,0,1,10,2,1,0,2016,2018,5,85396.0,BUCKEYE,Garage,Other,Concrete Tile,Cover,0.118001
6,262500,2477,0,1,9,3,2,1,2007,2019,4,85339.0,LAVEEN,Garage,Frame Wood,Concrete Tile,Cover,0.750553
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2168,142900,1423,0,1,7,2,0,1,2005,2014,4,85339.0,LAVEEN,Garage,Frame Wood,Concrete Tile,NaN,0.758593
2169,295000,2900,0,1,13,3,2,0,2014,2014,7,85338.0,GOODYEAR,Garage,Other,Concrete Tile,Cover,0.896997
2171,164500,1952,0,1,9,2,1,1,1999,2012,12,85374.0,SURPRISE,Garage,Frame Wood,Concrete Tile,Cover,0.712727
2174,765000,2571,450,1,11,2,2,0,1984,2017,10,85258.0,SCOTTSDALE,Garage,Frame Wood,Tile,Cover,0.880557
2175,465000,2763,500,1,12,2,2,0,1997,2017,8,85284.0,TEMPE,Garage,Frame Wood,Concrete Tile,Cover,0.223575

In [7]:
results2 = smf.ols("sale_price ~ area + single_story", data=df).fit()
print(results2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             sale_price   R-squared:                       0.513
Model:                            OLS   Adj. R-squared:                  0.513
Method:                 Least Squares   F-statistic:                     717.6
Date:                Thu, 14 Nov 2024   Prob (F-statistic):          1.73e-213
Time:                        13:59:43   Log-Likelihood:                -17735.
No. Observations:                1363   AIC:                         3.548e+04
Df Residuals:                    1360   BIC:                         3.549e+04
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -6.235e+04   1.11e+04     -5.609      0.000   -8.42e+04   -4.05e+04
area           145.1764      3.849     37.715      0.000     137.625     152.728
single_story  7.429e+04   6468.300     11.486      0.000    6.16e+04     8.7e+04
==============================================================================
Omnibus:                      271.883   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1223.005
Skew:                           0.872   Prob(JB):                    2.68e-266
Kurtosis:                       7.300   Cond. No.                     9.83e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.83e+03. This might indicate that there are
strong multicollinearity or other numerical problems.