In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Maricopa.xlsx')
df

,sale_price,area,pool_area,central_AC,fixtures,garage_count,patio_count,single_story,year_built,year_sold,month_sold,zipcode,city,garage_type,wall,roof,patio_type
0,345000,2015,0,1,7,2,1,1,2001,2018,6,85374.0,SURPRISE,Garage,Frame Wood,Concrete Tile,Cover
1,377500,2919,475,1,11,3,1,1,1991,2019,1,85048.0,PHOENIX,Garage,Frame Wood,Concrete Tile,Cover
2,423039,2044,0,1,7,3,1,1,2016,2017,9,85383.0,PEORIA,Garage,Other,Concrete Tile,Cover
3,333341,1754,0,1,7,2,2,1,2016,2016,11,85085.0,PHOENIX,Garage,Other,Concrete Tile,Cover
4,207000,1680,420,1,8,2,1,1,2003,2017,3,85379.0,SURPRISE,Garage,Frame Wood,Concrete Tile,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2173,235500,1656,461,1,6,2,1,1,1973,2016,9,85053.0,PHOENIX,Garage,8 Inch Painted Block,Asphalt Shingle,Slab
2174,765000,2571,450,1,11,2,2,0,1984,2017,10,85258.0,SCOTTSDALE,Garage,Frame Wood,Tile,Cover
2175,465000,2763,500,1,12,2,2,0,1997,2017,8,85284.0,TEMPE,Garage,Frame Wood,Concrete Tile,Cover
2176,270000,1614,0,1,7,2,1,1,1996,2016,4,85248.0,SUN LAKES,Garage,8 Inch Stucco,Concrete Tile,Cover
2177,166000,1738,0,1,6,2,1,1,1979,2017,5,85375.0,SUN CITY WEST,Garage,Frame Wood,Asphalt Shingle,Cover

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2178 entries, 0 to 2177
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sale_price    2178 non-null   int64
 1   area          2178 non-null   int64
 2   pool_area     2178 non-null   int64
 3   central_AC    2178 non-null   int64
 4   fixtures      2178 non-null   int64
 5   garage_count  2178 non-null   int64
 6   patio_count   2178 non-null   int64
 7   single_story  2178 non-null   int64
 8   year_built    2178 non-null   int64
 9   year_sold     2178 non-null   int64
 10  month_sold    2178 non-null   int64
 11  zipcode       2174 non-null   float64
 12  city          2174 non-null   object
 13  garage_type   2109 non-null   object
 14  wall          2178 non-null   object
 15  roof          2178 non-null   object
 16  patio_type    1926 non-null   object
dtypes: float64(1), int64(11), object(5)
memory usage: 289.4+ KB

In [4]:
df['single_story'].unique()

array([1, 0])

In [5]:
df['single_story'].value_counts()

single_story
1    1604
0     574
Name: count, dtype: int64

In [11]:
import statsmodels.formula.api as smf

In [15]:
results = smf.ols('sale_price ~ area + single_story', data=df).fit()

In [18]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             sale_price   R-squared:                       0.546
Model:                            OLS   Adj. R-squared:                  0.545
Method:                 Least Squares   F-statistic:                     1306.
Date:                Tue, 22 Oct 2024   Prob (F-statistic):               0.00
Time:                        14:22:21   Log-Likelihood:                -28235.
No. Observations:                2178   AIC:                         5.648e+04
Df Residuals:                    2175   BIC:                         5.649e+04
Df Model:                           2
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept    -8.785e+04   9122.686     -9.630      0.000   -1.06e+05      -7e+04
area           154.8458      3.048     50.795      0.000     148.868     160.824
single_story  7.686e+04   5436.712     14.137      0.000    6.62e+04    8.75e+04
==============================================================================
Omnibus:                      357.956   Durbin-Watson:                   1.951
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1555.333
Skew:                           0.730   Prob(JB):                         0.00
Kurtosis:                       6.874   Cond. No.                     1.03e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [19]:
results = smf.ols('sale_price ~ single_story', data=df).fit()

In [20]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             sale_price   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.006
Method:                 Least Squares   F-statistic:                     14.95
Date:                Tue, 22 Oct 2024   Prob (F-statistic):           0.000113
Time:                        14:28:27   Log-Likelihood:                -29086.
No. Observations:                2178   AIC:                         5.818e+04
Df Residuals:                    2176   BIC:                         5.819e+04
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     3.205e+05   6373.106     50.294      0.000    3.08e+05    3.33e+05
single_story -2.872e+04   7426.392     -3.867      0.000   -4.33e+04   -1.42e+04
==============================================================================
Omnibus:                      654.663   Durbin-Watson:                   1.986
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1751.505
Skew:                           1.595   Prob(JB):                         0.00
Kurtosis:                       6.020   Cond. No.                         3.67
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.